//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendPie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaAccount
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AccountType { get; set; }
        public string UserName { get; set; }
        public string ProfileName { get; set; }
        public Nullable<int> NumberOfTweets { get; set; }
        public Nullable<int> NumberOfFollowering { get; set; }
        public Nullable<int> NumberOfFollowers { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
