//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendPie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCampaign
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int CampaignID { get; set; }
        public Nullable<decimal> AmountEarned { get; set; }
        public System.DateTime DateJoined { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual User User { get; set; }
    }
}
